data:
dataset: Brain2D
data_path:
/scratch_hive/dp4018/data/ultrasound-data/Ultrasound-Vp-axial-models/→
mode: vp
maxsamples: null
slowness: false
resize:
- 256
- 256
clip_outliers: false
log: true
to_tensor: false
normalise: false
condition:
mode: null
resize: null
antialias: false
scale: null
clip_outliers: false
to_tensor: false
normalise: false
dataset_path: invldm/datasets
antialias: true
scale: null
sampling:
in_size:
- 64
- 64
in_channels: 3
sampling_only: false
logging:
tool: JSON
plot:
vmin: 0.3
vmax: 1.0
cmap: oscar
track_folder: exps/thesis/axial/base/JSON
logger: !!python/object/apply:logging.getLogger []
autoencoder:
model:
spatial_dims: 2
in_channels: 1
out_channels: 1
num_res_blocks: 2
num_channels:
- 64
- 128
- 128
attention_levels:
- false
- false
- true
latent_channels: 3
norm_num_groups: 32
norm_eps: 1.0e-06
with_encoder_nonlocal_attn: false
with_decoder_nonlocal_attn: false
use_flash_attention: false
use_checkpointing: false
use_convtranspose: false
checkpoint: null
params:
recon_loss: l1
recon_weight: 1.0
kl_weight: 1.0e-06
perceptual_loss: lpips
perceptual_weight: 1.0
lpips_model: vgg
wiener_mode: reverse
wiener_filter_dim: 2
wiener_filter_scale: 2
wiener_epsilon: 2.0
wiener_laplace_alpha: -0.2
wiener_laplace_beta: 1.5
wiener_weight: 0.0
adversarial_mode: least_squares
disc_n_layers: 2
disc_feature_channels: 16
adversarial_weight: 0.1
training:
batch_size: 16
n_epochs: 75
warm_up_epochs: 5
save_recon_freq: 2000
ckpt_freq: 500
ckpt_last_only: true
sampling_freq: 0
validation:
split: 0.0
batch_size: 0
freq: 0
save_recon_freq: 0
optim:
weight_decay: 0.0
optimiser: Adam
lr: 0.0001
d_lr: 0.0005
beta1: 0.9
amsgrad: false
eps: 1.0e-08
grad_clip: null
lr_scheduler:
scheduler: null
name: autoencoder
log_path: exps/thesis/axial/base/logs/autoencoder
ckpt_path: exps/thesis/axial/base/logs/autoencoder/checkpoints
recon_path: exps/thesis/axial/base/logs/autoencoder/recons
sampling_only: false
diffusion:
model:
num_res_blocks: 2
num_channels:
- 64
- 128
- 256
- 512
Pelacani Cruz, D. 281
attention_levels:
- false
- true
- true
- true
norm_num_groups: 32
norm_eps: 1.0e-06
resblock_updown: false
num_head_channels: 8
transformer_num_layers: 3
upcast_attention: false
use_flash_attention: false
checkpoint: null
params:
recon_loss: l2
beta_start: 0.0015
beta_end: 0.0205
num_train_timesteps: 1000
num_inference_timesteps: 50
schedule: linear_beta
sampler: ddim
training:
batch_size: 16
n_epochs: 400
ckpt_freq: 100
ckpt_last_only: true
sampling_freq: 2000
validation:
split: 0.0
batch_size: 0
freq: 0
save_recon_freq: 0
optim:
weight_decay: 0.0001
optimiser: Adam
lr: 2.0e-05
beta1: 0.9
amsgrad: false
eps: 1.0e-08
grad_clip: null
lr_scheduler:
scheduler: null
name: diffusion
log_path: exps/thesis/axial/base/logs/diffusion
ckpt_path: exps/thesis/axial/base/logs/diffusion/checkpoints
samples_path: exps/thesis/axial/base/logs/diffusion/samples
sampling_only: false
run:
config: exps/thesis/config_axial.yml
logdir: exps/thesis/axial
name: base
comment: ''
jobid: 7990
device: cuda
gpu_ids:
- 0
seed: 42
resume_training: false
overwrite: true
y: true
verbose: info
exp_folder: exps/thesis/axial/base
log_folder: exps/thesis/axial/base/logs
pid: 835743